3.user-guide=使用指南
1.learn-more-about-oceanbase=OceanBase 介绍
3.compatibility-with-oracle-1=与 Oracle 兼容性对比
3.deploy-the-oceanbase-database=部署数据库
3.preparations-before-deployment-1=部署前准备
5.graphical-interface-deployment=图形化界面部署
1.configure-a-deployment-environment=部署环境配置
2.deploy-ocp=部署 OCP
3.deploy-the-oceanbase-cluster=部署 OceanBase 集群
4.deploy-obproxy=部署 OBProxy
5.create-an-oceanbase-tenant=创建 OceanBase 租户
6.deploy-the-oms=部署 OMS
7.deploy-odc=部署 ODC
6.command-line-deployment=命令行部署
1.configure-a-deployment-environment-2=部署环境配置
2.deploy-ocp-4=部署 OCP
3.deploy-the-oceanbase-cluster-2=部署 OceanBase 集群
4.deploy-obproxy-4=部署 OBProxy
5.create-an-oceanbase-tenant-2=创建 OceanBase 租户
6.deploy-the-oms-4=部署 OMS
7.deploy-odc-4=部署 ODC
4.data-migration-1=数据迁移
3.use-obloader-and-obdumper-for-data-migration=使用 OBLOADER 和 OBDUMPER 迁移
5.database-connection-and-routing=数据库连接和路由
2.obproxy-management=管理 OBProxy
2.manage-obproxy-clusters=管理 OBProxy 集群
3.obproxy-management-2=管理 OBProxy
3.database-connection=连接数据库
5.logical-connection=逻辑连接
6.driver-management-1=驱动管理
7.route-management=路由管理
4.odp-routing-policy=ODP 路由策略
6.basic-database-management=集群和多租户管理
1.manage-clusters=管理集群
3.manage-cluster-parameters=管理集群参数
4.manage-zones-in-a-cluster=管理集群中的 Zone
5.manage-observer=管理 OBServer
2.configuration-management=配置管理
3.manage-resources=管理资源
3.management-resource-unit=管理资源单元
5.manage-resource-pools-1=管理资源池
4.manage-tenants-1=管理租户
4.manage-tenants-2=管理租户
5.manage-users-and-permissions=管理用户和权限
1.users-and-permissions=用户及权限介绍
2.oracle-3=Oracle 模式
9.manage-roles=管理角色
3.mysql-3=MySQL 模式
13.manage-tenant-parameters=管理租户参数
5.manage-data-storage=管理数据存储
1.dump-management-1=转储管理
2.merge-management-1=合并管理
3.data-compression-1=数据压缩
7.memory-management-1=管理内存
8.management-process=管理进程
9.manage-logs=管理日志
2.log-print-level=日志打印级别
3.manage-the-size-and-quantity-of-log-files-2=日志文件大小及数量管理
4.view-logs-2=查看日志
7.database-object-management-1=数据库对象管理
1.oracle-4=Oracle 模式
1.manage-tables-1=管理表
2.manage-a-table-group-1=管理表组
3.manage-indexes-1=管理索引
7.manage-triggers=管理触发器
2.mysql-4=MySQL 模式
1.manage-databases-1=管理数据库
2.manage-tables-2=管理表
3.manage-a-table-group-2=管理表组
4.manage-indexes-2=管理索引
6.manage-triggers-1=管理触发器
8.distributed-storage-management=分布式存储管理
2.manage-partition-table=管理分区
1.oracle-1=Oracle 模式
9.create-partition-table-index-2=创建分区表索引
2.mysql-1=MySQL 模式
9.create-partition-table-index-3=创建分区表索引
3.manage-partition-table-table-groups=管理分区表表组
1.oracle-8=Oracle 模式
2.mysql-8=MySQL 模式
4.manage-replicas=管理副本
5.locality-management-1=管理 Locality
9.sql-optimization=SQL 调优
2.sql-execution-plan=SQL 执行计划
2.execution-plan-operator=执行计划算子
3.distributed-execution-plan=分布式执行计划
4.sql-optimization-1=SQL 优化
3.monitor-sql-execution-performance=SQL 执行性能监控
4.sql-performance-analysis-example=SQL 性能分析示例
4.optimizer-statistics=优化器统计信息
2.statistics-collection-methods=统计信息收集方式
3.statistics-management=统计信息管理
5.query-rewrite=查询改写
6.query-optimization=查询优化
1.access-path=访问路径
2.join-algorithm=联接算法
7.manage-execution-plans=管理执行计划
11.data-security-management=数据库安全
1.data-storage-encryption=数据存储加密
2.mysql-2=MySQL 模式
3.oracle-2=Oracle 模式
2.transmission-encryption=数据传输加密
4.audit-database=审计数据库
10.high-data-availability=高可用和容灾
1.flashback=闪回
2.backup-and-restoration-management=备份恢复管理
3.log-archive=日志归档
1.log-archive-by-using-the-command-line=通过命令行
4.data-backup=数据备份
1.data-backup-by-using-the-command-line=通过命令行
5.cleaning-up-backed-up-data=清理备份
1.cleaing-up-by-using-the-command-line=通过命令行
6.restore-data=恢复数据
2.restore-by-using-the-command-line=通过命令行
11.troubleshooting-common-issues-1=常见问题排查
12.o-m-management=运维管理
1.o-m-overview=运维概述
2.introduction-to-operations-and-maintenance-tools=运维工具介绍
2.scale-out-and-scale-in-1=扩容和缩容
2.cluster-level-scale-out-and-scale-in=集群级别的扩容和缩容
1.scale-out=扩容
2.shrink-1=缩容
3.scale-in-and-scale-out-of-tenant-resources=租户内资源的扩容和缩容
3.upgrade-guide=升级指南
4.monitoring-and-alerting=监控和告警
2.monitoring-1=监控
3.alert-1=告警
5.daily-inspection=日常巡检
2.full-link-detection=全链路诊断
6.performance-diagnosis=性能诊断
7.troubleshooting=问题排查
2.problem-locating=问题定位
8.emergency-response=应急处理
3.common-emergency-response=常见应急问题处理
1.issues-in-the-hardware-environment=硬件环境导致的问题
2.problems-caused-by-capacity-changes=容量变化导致的问题
3.other-problems-within-the-cluster=集群内部其他问题
9.common-o-m-operations=常用运维操作
1.service=服务相关
2.resource=资源相关
3.storage=存储相关
4.data-related-functions=数据相关
5.performance=性能问题
3.sql-diagnostics=SQL 诊断
14.system-reference=系统参考
1.system-configuration-items=系统配置项
3.cluster-level-configuration-items-1=集群级别配置项
4.tenant-level-configuration-items-1=租户级别配置项
2.system-variable-for-mysql=系统变量（MySQL 模式）
3.system-variable-for-oracle=系统变量（Oracle 模式）
4.system-view-for-mysql=系统视图（MySQL 模式）
2.dictionary-view-5=字典视图
3.performance-view-5=性能视图
5.system-view-for-oracle=系统视图（Oracle 模式）
2.dictionary-view-6=字典视图
3.performance-view-6=性能视图
6.error-code-for-mysql=错误码（MySQL 模式）
7.error-code-for-oracle=错误码（Oracle 模式）
15.faq=常见问题
4.development-guide-refactoring-1=开发指南
2.application-development-based-on-mysql-mode=基于 Mysql 模式进行应用开发
1.client-connects-to-oceanbase-database=客户端连接 OceanBase 数据库
2.application-development-2=应用程序开发
1.java-application=Java 应用程序
3.c-application=C 应用程序
3.create-and-manage-database-objects=创建和管理数据库对象
4.data-type=数据类型
5.create-a-database-object-using-odc=使用 ODC 创建数据库对象
6.create-and-manage-tables=创建和管理表
7.create-and-manage-partition-table=创建和管理分区表
8.create-and-manage-indexes=创建和管理索引
9.create-and-manage-table-groups=创建和管理表组
2.create-table-group=创建表组
10.create-and-manage-views=创建和管理视图
11.managing-and-creating-sequences=管理和创建序列
12.create-and-manage-triggers=创建和管理触发器
4.query=查询
8.multi-table-join-queries=多表关联查询
9.use-operators-and-functions-in-queries=在查询中使用操作符和函数
10.execution-plan=执行计划
5.about-dml-statements-and-transactions=关于 DML 语句和事务
1.dml-statement=DML 语句
2.transaction=事务
3.Application-development-based-on-Oracle-mode=基于 Oracle 模式进行应用开发
1.Client-connection-to-oceanbase-database=客户端连接 OceanBase 数据库
2.application-development-1=应用程序开发
1.java-application-1=Java 应用程序
2.python-application-1=Python 应用程序
3.c-application-1=C 应用程序
3.Create-and-manage-database-objects=创建和管理数据库对象
04.Creating-database-objects-using-ODC=使用 ODC 创建数据库对象
05.Data-type=数据类型
06.Create-and-manage-tables=创建和管理表
07.Create-and-manage-partition-tables=创建和管理分区表
08.Create-and-manage-indexes=创建和管理索引
09.Create-and-manage-table-groups=创建和管理表组
02.create-table-group=创建表组
10.Create-and-manage-views=创建和管理视图
11.Create-and-manage-sequences=管理和创建序列
12.Create-and-manage-synonyms=管理和创建同义词
13.Create-and-manage-triggers=创建和管理触发器
4.Query-table-data=查询
08.Multi-table-Association-query=多表关联查询
09.Use-operators-and-functions-in-queries=在查询中使用操作符和函数
10.Execution-plan=执行计划
5.about-DML-statements-and-transactions=关于 DML 语句和事务
01.DML-statements=DML 语句
02.transactions=事务
4.migrate-data=迁移数据
3.exporting-and-importing-data-using-odc=使用 ODC 导出和导入数据
4.migrate-data-by-using-sql-scripts=使用 SQL 脚本迁移
6.use-obloader-and-obdumper-for-data-migration-1=使用 OBLOADER & OBDUMPER 迁移
7.use-datax-to-migrate-data=使用 DataX 迁移
5.database-design-specifications-and-practices=设计规范和约束
01.object-naming-conventions=对象命名规范
02.object-structure-design-specification=对象结构设计规范
05.database-design-best-practices=数据库设计实践
01.database-connection-pool-configuration-example=数据库连接池配置示例
02.development-framework-connection-database-example=开发框架连接数据库示例
6.sql-syntax=SQL 语法
1.system-tenants=系统租户
2.alter-system=ALTER SYSTEM
2.common-tenant-mysql-mode=普通租户（MySQL 模式）
1.basic-elements=基本元素
1.data-type=数据类型
2.numeric-1=数值类型
3.date-and-time-types-1=日期时间类型
4.string-2=字符类型
5.large-object-1=大对象和文本类型
8.json-formatted-data-type=JSON 数据类型
2.expression-2=表达式
3.character-set-and-collation=字符集与字符序
4.literal=字面量
2.operator=运算符
4.functions=函数
2.functions-1=单行函数
1.date-and-time-functions-1=日期时间函数
2.string-functions=字符串函数
3.conversion-functions-1=转换函数
4.mathematical-functions=数学函数
5.comparison-functions=比较函数
6.process-control-functions=流程控制函数
3.aggregate-function=聚合函数
4.analysis-functions-1=分析函数
5.encryption-functions=加密函数
6.information-functions=信息函数
7.json-functions=JSON 函数
1.create-a-function-with-json-text=创建 JSON 文本的函数
2.a-function-to-search-for-json-text=搜索 JSON 文本的函数
3.function-to-modify-json-text=修改 JSON 文本的函数
4.function-that-returns-the-json-text-property=返回 JSON 文本属性的函数
5.json-functions-1=JSON 工具函数
6.json-aggregate-functions=JSON 聚合函数
8.other-functions=其它函数
5.queries-and-subqueries=查询和子查询
6.sql-statement=SQL语句
51.select-1-2=SELECT 
7.ddl-function=DDL 功能
3.common-tenant-oracle-mode=普通租户（Oracle 模式）
2.pseudo-column-1=伪列
3.basic-elements-1=基本元素
1.built-in-data-types=内建数据类型
2.character-data-type=字符数据类型
3.numeric-data-type=数值数据类型
4.date-time-and-interval-data-types=日期时间和间隔数据类型
6.large-object-data-type=大对象数据类型
2.data-type-comparison-rules=数据类型比较规则
3.literal-1=字面量
4.date-and-time-literal=日期时间字面量
4.format=格式模型
5.null=空值
6.annotation-1=注释
4.Hint=Hint
2.hint-list=Hint 清单
7.database-objects=数据库对象
8.database-naming-convention=数据库命名规范
9.database-object-reference-method=数据库对象引用方式
3.reference-objects-in-a-remote-database=引用远程数据库中的对象
4.operator-1=运算符
5.functions-2=函数
2.single-row-functions=单行函数
1.numeric-functions=数字函数
2.string-functions-that-return-a-string=返回字符串的字符串函数
3.string-functions-that-return-numbers=返回数字的字符串函数
4.date-and-time-functions=时间日期函数
5.generic-comparison-functions=通用比较函数
6.conversion-functions=转换函数
7.encoding-and-decoding-functions=编码解码函数
8.null-value-related-function=空值相关函数
9.environment-and-identifier-functions=环境和标识符函数
10.hierarchical-functions=层次函数
3.aggregate-functions=聚合函数
4.analysis-functions-2=分析函数
6.expression-1=表达式
7.condition=条件
8.queries-and-subqueries-1=查询和子查询
9.sql-statement-1=SQL 语句
1.DDL-1=DDL
2.DML=DML
5.SELECT-1=SELECT
3.DCL=DCL
10.ddl-function-1=DDL 功能
7.pl-reference=PL 参考
1.what-is-pl-1=什么是 PL
2.pl-mysql=PL 参考（MySQL 模式）
2.storage-object=PL 存储程序
3.cursor=PL 游标
4.control-statement=PL 条件控制语句
5.pl-manipulation-statement=PL 数据操作语句
6.sql-statements-for-pl-stored-programs=PL 数据定义语句
7.pl-database-management-statements=PL 数据库管理语句
8.information_schema-dictionary-view=PL 相关字典视图
9.pl-exception-handling-statement=PL 异常处理
10.pl-system-package=PL 系统包
1.DBMS_RESOURCE_MANAGER=DBMS_RESOURCE_MANAGER
2.DBMS_STATS=DBMS_STATS
3.pl-oracle=PL 参考（Oracle 模式）
1.pl-language-basics-1=PL 语言基础
2.data-type-1=PL 数据类型
3.process-control=PL 流程控制
4.collections-and-records=PL 集合与记录
7.collection-methods=集合方法
5.pl-static-sql=PL 静态 SQL
2.cursor=游标
4.autonomous-transactions=自治事务
6.dynamic-sql=PL 动态 SQL
7.stored-procedure-and-functions=PL 存储过程与函数
6.pipeline-function=管道函数
7.user-defined-aggregation-functions=用户自定义函数
8.trigger=PL 触发器
9.package=PL 程序包
10.exception-handling-1=PL 异常处理
11.ddl-operations-on-stored-pl-units=对已存储 PL 单元的 DDL 操作
12.pl-system-package=PL 系统包
2.DBMS_AUDIT_MGMT=DBMS_AUDIT_MGMT
3.DBMS_APPLICATION_INFO=DBMS_APPLICATION_INFO
4.DBMS_CRYPTO=DBMS_CRYPTO
5.DBMS_DEBUG=DBMS_DEBUG
6.DBMS_DESCRIBE=DBMS_DESCRIBE
7.DBMS_JOB=DBMS_JOB
8.DBMS_LOB=DBMS_LOB
9.DBMS_LOCK=DBMS_LOCK
10.DBMS_METADATA-1=DBMS_METADATA
11.DBMS_OUTPUT=DBMS_OUTPUT
12.DBMS_PLAN_CACHE=DBMS_PLAN_CACHE
13.DBMS_RANDOM=DBMS_RANDOM
14.DBMS_SCHEDULER=DBMS_SCHEDULER
15.DBMS_SESSION=DBMS_SESSION
16.DBMS_SQL=DBMS_SQL
17.DBMS_STATS=DBMS_STATS
18.DBMS_UTILITY=DBMS_UTILITY
19.DBMS_XA=DBMS_XA
20.DBMS_XMLGEN=DBMS_XMLGEN
21.XMLType=XMLType 
22.ODCICONST=ODCICONST
23.UTL_FILE=UTL_FILE
24.UTL_ENCODE=UTL_ENCODE
25.UTL_I18N=UTL_I18N
26.UTL_RAW=UTL_RAW
27.anydata-type=anydata-type
13.pl-label-security-package-1=PL 标签安全包
2.sa_sysdba-policy-management-package=SA_SYSDBA 策略管理包
3.sa_components-tag-package=SA_COMPONENTS 标签组件包
4.sa_label_admin-tag-management-pack=SA_LABEL_ADMIN 标签管理包
5.sa_policy_admin-policy-management-packs=SA_POLICY_ADMIN 策略管理包
6.sa_user_admin-user-tag-management-pack=SA_USER_ADMIN 用户标签管理包
7.sa_session-session-management-pack=SA_SESSION 会话管理包
8.sql-specifications-and-practices=SQL 实践和建议
02.sql-writing-Specification=SQL 编写规范
03.sql-statement-example=SQL 语句示例
9.common-errors-and-solutions=常见报错与处理
1.MySQL=MySQL
03.timeout=超时相关
04.user-2=用户相关
05.table-related-functions=表相关
06.constraint-related-functions=约束相关
07.sql-related-commands=SQL 相关
2.Oracle=Oracle
03.timeout-related=超时相关
04.user-related=用户相关
05.object-related=对象相关
06.constraint-related=约束相关
07.sql-related=SQL 相关
5.concepts-of-oceanbase-database-system=系统架构
3.multi-tenant-architecture-1=多租户架构
5.tenants-and-resource-management-1=租户与资源管理
4.database-objects-1=数据库对象
1.oracle=Oracle 模式
1.introduction-to-database-objects=数据库对象介绍
2.table=表
2.data-type-2=数据类型
7.format-model=格式模型
3.index=索引
4.partition=分区
5.view-1=视图 
6.other-objects=其他对象
7.system-view-1=系统视图
8.data-integrity=数据完整性
2.integrity-constraint-type=完整性约束类型
2.mysql=MySQL 模式
1.introduction-to-database-objects-1=数据库对象介绍
2.table-1=表
2.data-type-3=数据类型
3.index-1=索引
4.partition-2=分区
5.view-2=视图
6.system-view-2=系统视图
7.data-integrity-1=数据完整性
2.integrity-constraint-type-1=完整性约束类型
5.distributed-database-objects=分布式数据库对象
3.data-partitions-and-replicas=数据分区和分区副本
3.partition-replica-type=分区副本类型
5.data-balancing-1=数据均衡
1.partition-copy-balancing=分区副本均衡
2.leader-equalization=Leader 均衡
4.dynamic-scaling=动态扩容和缩容
2.scale-in-and-scale-out-of-tenant-resources-1=租户内资源的扩容和缩容
6.data-link-1=数据链路
2.database-proxy-1=数据库代理
3.database-driver-1=数据库驱动
7.user-interface-and-query-language=用户接口和查询语言
1.SQL=SQL
1.sql-introduction=SQL 介绍
2.sql-statement-2=SQL 语句
5.distributed-execution-plan-2=分布式执行计划
2.PL=PL
1.pl-concepts=PL 概念
1.oracle-6=Oracle 模式
2.mysql-6=MySQL 模式
8.transaction-management-1=事务管理
1.transaction-2=事务
5.transaction-control=事务控制
4.transactional-control-statement=事务控制语句
8.distributed-transactions-1=分布式事务
2.transaction-concurrency-and-consistency=事务并发和一致性
3.concurrency-control-1=并发控制
4.transaction-isolation-level=事务隔离级别
9.storage-architecture-1=存储架构
2.data-storage=数据存储 
3.dump-and-merge-1=转储和合并
6.data-integrity-2=数据完整性
10.high-data-reliability-and-availability=数据可靠性和高可用
1.high-availability-architecture=高可用架构
3.primary-secondary-database-1=主备库
4.data-protection=数据保护
5.backup-and-restoration=备份恢复
11.database-security=数据库安全
12.observer-node-architecture=OBServer 节点架构
3.observer-thread-model=observer 线程模型
5.memory-management=内存管理
7.version-release-records=版本发布记录
1.version-release-records-2=版本发布记录